name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Set environment variables from GitHub secrets
      run: |
        echo "MAVEN_OPTS=-Dlogin.username=${{ secrets.LOGIN_USERNAME }} \
         -Dlogin.password=${{ secrets.LOGIN_PASSWORD }}" >> $GITHUB_ENV
  
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    
