name: Java CI with Maven

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      # - name: Install Chrome
      #   run: |
      #     Invoke-WebRequest -Uri https://dl.google.com/chrome/install/latest/chrome_installer.exe -OutFile chrome_installer.exe
      #     Start-Process chrome_installer.exe -ArgumentList '/silent', '/install' -NoNewWindow -Wait
      #     Remove-Item chrome_installer.exe
       
      # - name: Install ChromeDriver
      #   run: |
      #     $chromeVersion = (Get-Command chrome).FileVersionInfo.ProductVersion
      #     $chromeDriverVersion = $chromeVersion.Split('.')[0..1] -join '.'
      #     Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeDriverVersion)/chromedriver_win32.zip" -OutFile chromedriver.zip
      #     Expand-Archive chromedriver.zip -DestinationPath C:\chromedriver
      #     Remove-Item chromedriver.zip
      #     Move-Item C:\chromedriver\chromedriver.exe C:\Windows\System32

      # - name: Check Chrome Version
      #   run: |
      #     $chromeVersion = (Get-Command chrome).FileVersionInfo.ProductVersion
      #     Write-Output "Chrome version: $chromeVersion"

      - name: Check ChromeDriver Version
        run: chromedriver --version

      - name: Build and Run Tests with Maven
        run: |
          mvn clean test -Dlogin.username="${{secrets.LOGIN_USERNAME}}" -Dlogin.password="${{secrets.LOGIN_PASSWORD}}" -f practice/pom.xml
      
      - name: Upload Screenshot Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-screenshot
          path: practice/target/dashboard_screenshot.png
